baseURL = "https://chemea-ocb.pages.dev/"
languageCode = "en-us"
title = "Chemea™ Oman Carbon Black (OCB)"
theme = ""

[pagination]
  pagerSize = 10

[params]
  description = "Global carbon black trading leader"
  author = "Chemea"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
